name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Market Insider(시장지수).json" -e "40443175-1c302d5e-5930-4579-880f-ce404a2c4b29" --integration-id "174296-${{ github.run_id }}"
          postman collection run "${{ github.workspace }}/postman/collections/코인 API (Binance).json" -e "40443175-55f8a2ab-0dc1-48a9-8279-59b370c19d78" --integration-id "174296-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 6217c316-7560-466c-a64d-28fbf7f82888 --integration-id 174296
